apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: deploy-web
  name: deploy-web
  namespace: karasuit
spec:
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deploy-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-web
    spec:
      serviceAccountName: default
      containers:
        - image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          name: web
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
